### PR TITLE
Moderately less disruptive

### PR DESCRIPTION
**Pull request by paulfalgout**
But still really bad

### CODE REVIEW

**Comment by jamesplease** [comment]
I tried to make it show the loader **and** show the squares, and I wasn't able to make it work.

I did this + `setTimeout()` of 0 on the drawing of squares. Were you able to make it do both, @paulfalgout ?

**Comment by paulfalgout** [comment]
ummm maybe not?  my bad.. coulda sworn it worked, but I may have been imagining things.  Doing to many things at once :-/

**Comment by paulfalgout** [comment]
`alert('loading..')` it is I guess

**Comment by jamesplease** [comment]
> ummm maybe not? my bad.. coulda sworn it worked, but I may have been imagining things. Doing to many things at once :-/

heh, no problem. I know how that is :stuck_out_tongue: 

> alert('loading..') it is I guess

I'm thinking that the `alert` is functioning in the same way that the `setTimout(..., 100);` is – adding a forced delay between the two DOM ops. I wonder if we had the ability to force the alert to immediately resolve if it would still batch the ops :question: I think it would!

**Pull request closed without merging**
